// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoiOgCoCszkhiCy_TAkKoSC1DWM57ejis',
    appId: '1:115688405848:web:19d5f37b587bf76004432d',
    messagingSenderId: '115688405848',
    projectId: 'valley-f2ea1',
    authDomain: 'valley-f2ea1.firebaseapp.com',
    storageBucket: 'valley-f2ea1.firebasestorage.app',
    measurementId: 'G-3JDY2WMQYH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPAJz4h9oK1bsIf8cmCdxNd8e-RQRHbLU',
    appId: '1:115688405848:android:e4cc167dde647f7004432d',
    messagingSenderId: '115688405848',
    projectId: 'valley-f2ea1',
    storageBucket: 'valley-f2ea1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuf3DifgOIDco76IH5NuXcQ-Rmk8LvkS4',
    appId: '1:115688405848:ios:909ca7a44330fa3404432d',
    messagingSenderId: '115688405848',
    projectId: 'valley-f2ea1',
    storageBucket: 'valley-f2ea1.firebasestorage.app',
    androidClientId: '115688405848-1kine59pggknovn9gmbvgngt0vfn7sfe.apps.googleusercontent.com',
    iosClientId: '115688405848-bhktucisghoo17af3tvh2u7rl5v749k2.apps.googleusercontent.com',
    iosBundleId: 'com.phlera.dentofly.seller',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuf3DifgOIDco76IH5NuXcQ-Rmk8LvkS4',
    appId: '1:115688405848:ios:909ca7a44330fa3404432d',
    messagingSenderId: '115688405848',
    projectId: 'valley-f2ea1',
    storageBucket: 'valley-f2ea1.firebasestorage.app',
    androidClientId: '115688405848-1kine59pggknovn9gmbvgngt0vfn7sfe.apps.googleusercontent.com',
    iosClientId: '115688405848-bhktucisghoo17af3tvh2u7rl5v749k2.apps.googleusercontent.com',
    iosBundleId: 'com.phlera.dentofly.seller',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoiOgCoCszkhiCy_TAkKoSC1DWM57ejis',
    appId: '1:115688405848:web:cb8216a8a40e1a4804432d',
    messagingSenderId: '115688405848',
    projectId: 'valley-f2ea1',
    authDomain: 'valley-f2ea1.firebaseapp.com',
    storageBucket: 'valley-f2ea1.firebasestorage.app',
    measurementId: 'G-VFP3J6TSYQ',
  );

}